server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_url_db?useSSL=false&serverTimezone=UTC
    username: root
    password: google.com1
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.shorturl.model
short-url:
  domain: http://short.url/
  length: 6
logging:
  level:
    com.example.shorturl: debug
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus